### ISSUE TITLE
When wrong order id is searched, a message of no orders present on the page appears

### ISSUE THREAD

**Issue by appurvajain** [hotwax/fulfillment-pwa#138]
When we search an order with a wrong id or using an order ID which is not present on the open orders or in-progress page, the message that appears says "Central Warehouse doesn't have any outstanding orders right now." 

It should say something like that "The order is not present on this page. Please search on other pages."

**Comment by ymaheshwari1** [comment]
We can make the message something like:

```
No results found for <keyword>. Try searching In Progress or Completed tab instead.
If you still can't find what you're looking for, try switching stores.
```
