### ISSUE TITLE
Unable to Generate Shipping Label in the In Progress Tab

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/fulfillment-pwa#178]
## Current behavior
When attempting to generate a shipping label in the In Progress tab, the process fails to generate the label. Upon selecting the option to generate the shipping label, a new tab opens but displays a blank screen instead.

## Expected behavior
The expected behavior is that when generating a shipping label in the In Progress, a new tab should open with the generated Shipping label. 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information
Blank screen in new tab: 
<img width="1434" alt="Screenshot 2023-07-11 at 5 55 41 PM" src="https://github.com/hotwax/fulfillment-pwa/assets/119936391/effe3ace-1b7b-488f-9c9e-eba3d0e1b5d7">

**Comment by Dhiraj1405** [comment]
Verified on Demo, its working succesfully. We can close this issue.

**Comment by ymaheshwari1** [comment]
Closing.
