### ISSUE TITLE
Display In-Stock Quantity in Order Card

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/fulfillment-pwa#182]
## What is the motivation for adding/enhancing this feature?
The Order card in our application does not display the in-stock quantity of the ordered item. This missing information makes it difficult for users to quickly assess the availability of the product in the store at the time of order processing.

## What are the acceptance criteria?
The Order card should include the in-stock quantity of the ordered item. By displaying this information, users can easily determine if there is sufficient stock to fulfill the order or if additional actions need to be taken to manage inventory.

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by dt2patel** [comment]
Thanks @Dhiraj1405 we will pick this after the first released version of this app.
