### ISSUE TITLE
Order Card Distortion and Missing Last Brokered Time when Adding More Than 6 Boxes

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/fulfillment-pwa#187]
## Current behavior
When adding more than 6 boxes to an order, the order card's information gets distorted, and the last brokered time is no longer displayed 

## Expected behavior
When more than 6 boxes are added to an order, the order card should dynamically adjust its layout to accommodate the additional information and the last brokered time should be consistently visible in the order card.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information
<img width="1440" alt="Screenshot 2023-07-12 at 3 07 29 PM" src="https://github.com/hotwax/fulfillment-pwa/assets/119936391/64cb4dcb-c407-4880-973d-00f821997d16">

**Comment by sanskar345** [comment]
The last brokered time does not depend on the boxes added or the boxes present. It is missing because of the missing data.
