### ISSUE TITLE
Implement product identifier using dxp-components.

### ISSUE THREAD

**Issue by sanskar345** [hotwax/fulfillment-pwa#210]
## What is the motivation for adding/enhancing this feature?

Add a product identifier card in settings so that the user can change the identifier of the products displayed in app as per his/her requirement.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

**Comment by ravilodhi** [comment]
Here is the PR for this - https://github.com/hotwax/fulfillment-pwa/pull/273/files
