### ISSUE TITLE
Manage Transfer Orders

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/fulfillment-pwa#235]
## What is the motivation for adding/enhancing this feature?
The new feature will allow users to manage transfer shipments through a dedicated page. Users can effortlessly view and ship the shipments.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

## Additional information
https://www.figma.com/file/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?type=design&node-id=12265%3A29969&mode=design&t=OZJNbBHnaXRArGf9-1

This is a reference UI, which is subject to change in sometime.

**Comment by Adameddy26** [comment]
Verified and working as expected in v2.0.1.
