### ISSUE TITLE
Display Store Order Limit on Online Order Fulfillment Card in the Settings Page

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/fulfillment-pwa#241]
## What is the motivation for adding/enhancing this feature?
The store's order limit should be displayed on the Online Order Fulfillment Card in Settings. This feature informs users of the day's remaining order capacity from the daily online order fulfillment limit for better visibility on order fulfillment.  

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Dhiraj1405** [comment]
@dt2patel Please review the UI: https://www.figma.com/file/wK5FMs4z2zXQR9VfHV9ycE/Dhiraj's-Ionic-6-Material-UI-Kit-(Community)?type=design&node-id=27889%3A100971&mode=design&t=GsGeGiQnE0hodmgi-1

**Comment by dt2patel** [comment]
Updated the proposed UI, its good to go from my side now.
