### ISSUE TITLE
Unable to Log Into App When User Is Already Logged Into Launchpad

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/fulfillment-pwa#248]
## Current behavior
Users are prompted to enter their credentials again, despite having already logged in to the Launchpad.

## Expected behavior
After logging in to the Launchpad, users should be granted seamless access to the application without needing to provide their credentials again.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by ymaheshwari1** [comment]
Will be fixed by https://github.com/hotwax/launchpad/pull/37

**Comment by dt2patel** [comment]
closing issue since MR has issue linked to it
