### ISSUE TITLE
Display Full Name for Single Assigned Picker in Picklist 

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/fulfillment-pwa#279]
## What is the motivation for adding/enhancing this feature?
Currently the picker name is truncated when there is only one picker. We should display the full name of the assigned picker on the In progress orders page when there is only one picker assigned to the pick list.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by madhurchouhan01** [comment]
Can you assign this task to me?

**Comment by k2maan** [comment]
Sure @madhurchouhan01 go ahead
