### ISSUE TITLE
Display No Variance Rejection Reasons for Order Items

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/fulfillment-pwa#292]
## What is the motivation for adding/enhancing this feature?
Our current order rejection process lacks a specific category for cases where the fulfillment teams need to reject an order without logging any inventory variance. To enhance the efficiency of our order processing workflow and facilitate more precise decision-making, it is crucial to introduce a dedicated rejection reason labeled as `No variance`.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Lavesh12** [comment]
can you assign me this issue?

**Comment by k2maan** [comment]
Sure @Lavesh12 go ahead
