### ISSUE TITLE
Create Order Detail Page

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/fulfillment-pwa#310]
## What is the motivation for adding/enhancing this feature?
Currently, there is no dedicated page that opens when a user clicks on an order card. We believe that having a detailed order detail page is crucial for providing a better user experience and enhancing the actions available to users.

## What are the acceptance criteria?
1. When a user clicks on an order card, open a dedicated order detail page displaying comprehensive information about the order.
2. Include details such as order ID, customer information, shipping address, payment method, and order date.- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

## Additional information
This page will be built in three different parts: 

- [x] #311
- [x] #312
- [x] #313

**Comment by Dhiraj1405** [comment]
[Please refer this UI](https://www.figma.com/file/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?type=design&node-id=29707%3A14605&mode=design&t=ULEbsteVX2G80cjW-1)

**Comment by dt2patel** [comment]
closing task since this is in production
