### ISSUE TITLE
Display Ship Group Sequence ID on Order Detail Page

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/fulfillment-pwa#332]
## What is the motivation for adding/enhancing this feature?
On the order detail page, the ship group sequence ID is not displayed, causing a lack of crucial information for order tracking and management. It is essential for users to have access to the ship group sequence ID to accurately identify and manage orders

## What are the acceptance criteria?
The ship group sequence ID should be displayed prominently on the order detail page, providing users with the necessary information to track and manage orders effectively.

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Dhiraj1405** [comment]
https://www.figma.com/file/wK5FMs4z2zXQR9VfHV9ycE/Dhiraj's-Ionic-6-Material-UI-Kit-(Community)?type=design&node-id=29258-164395&mode=design&t=chIMtrSgKa5wcmta-4

**Comment by Nidbhagwat** [comment]
@Dhiraj1405 Here is the UI link
https://www.figma.com/file/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?type=design&node-id=29707%3A14605&mode=design&t=juWvhZn4LOFHF3ii-1
