### ISSUE TITLE
All facilities should be visible to the Super users

### ISSUE THREAD

**Issue by appurvajain** [hotwax/fulfillment-pwa#336]
## Current behavior
Currently we need to associate a facility with the user even when the user has Super or Commerce Super/administrator permission. 

## Expected behavior
When a user has Super or Commerce Super/administrator permission, all active facilities should be visible to the user.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Dhiraj1405** [comment]
Discussed and already fixed in coming updates.
