### ISSUE TITLE
Shipping label error gets truncated

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/fulfillment-pwa#380]
## Current behavior

In current scenario the shipping label error gets truncated.

## Expected behavior

The error should be wrapped so that the complete message gets displayed on the UI

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Dhiraj1405** [comment]
We should add the option to copy the error message as well. 
@amansinghbais
