### ISSUE TITLE
Only 100 orders visible in completed tab

### ISSUE THREAD

**Issue by sanjanashrivastava** [hotwax/fulfillment-pwa#390]
## Current behavior
The completed tab restricts the display to only 100 orders at maximum, even when there are more than a hundred orders for shipment. Orders after 100th order cannot be shipped/viewed as a result.

## Expected behavior
Orders should load on the same page on scrolling, or next and previous page options to be provided. 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: Google Chrome - Version 120.0.6099.109
- OS: macOS Ventura 13.5.1 (22G90)
- Code Version: 

## Additional information
For reference, Fulfillment app in newera-uat can be checked, only 100 out of 618 orders are visible. 
<img width="1440" alt="Screenshot 2024-01-15 at 5 58 02 PM" src="https://github.com/hotwax/fulfillment-pwa/assets/155512107/fd48d072-910c-4b82-834f-bc49856968bd">

**Comment by ravilodhi** [comment]
This is kind of intentional as of now. So marking it as closed.
