### ISSUE TITLE
Update Destination Card to Reflect Correct Shipping Label Status for Orders Moved to In-Progress Page

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/fulfillment-pwa#408]
## Current behavior
Currently, when an order is moved from the open page to the in-progress page, the app initiates the process of obtaining the shipping label in the background. However, even when the shipping label is successfully generated, the destination card erroneously displays "missing shipping label." This discrepancy leads to confusion and inefficiencies in order processing. To ensure accurate representation of shipping label status for orders moved to the in-progress page, it is necessary to update the destination card functionality accordingly.

## Expected behavior
Adjust the logic within the destination card component to correctly reflect the presence of a generated shipping label for orders in the in-progress stage.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information
[Missing shipping label on the In Progress page](https://jam.dev/c/133e7815-4c84-44fa-a206-9ac0ec0dbd19)
[Missing shipping label on the Completed page](https://jam.dev/c/0f96ad30-d92d-4d9c-a94c-fb2cc725d8df)

**Comment by Adameddy26** [comment]
Issue verified in 2.0.1 and found that issue is still replicating.
https://jam.dev/c/54bd0d27-979a-4a41-b75c-900bc0d9198a
@ravilodhi Please connect with me wherever needed.

Also if shipping label is generated successfully, shipping label code is not visible in details page(In Progress).
https://jam.dev/c/d37e2047-f8e2-48d4-8655-6728040c2b34

**Comment by ravilodhi** [comment]
The mentioned issue has been fixed in the following PR - https://github.com/hotwax/fulfillment-pwa/pull/445
