### ISSUE TITLE
Quantity Not Updating Upon Picking Transfer Order Item via QR Code Scanner

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/fulfillment-pwa#418]
## Current behavior
The system fails to update the quantity picked upon scanning the QR code, resulting in an inaccurate representation of inventory levels and transfer order fulfillment status.

## Expected behavior
Upon scanning the QR code and confirming the picking action, the system should update the quantity picked for the respective transfer order item, ensuring accurate inventory tracking.

## Steps to reproduce the issue
Open the App and then go to Transfer Orders section.
Open any TO.
Scan the QR code associated with the item to indicate picking.
On successful scan, observe the issue.

## Environment details
- App Version: TRANSFER-ORDER-UI-D9CDF5B
- App Environment: UAT

## Additional information
https://jam.dev/c/7b74cf8b-be4f-4715-85db-07d5bdbcfe5b

**Comment by ravilodhi** [comment]
This issue has been fixed under following PR - https://github.com/hotwax/fulfillment-pwa/pull/412
