### ISSUE TITLE
Separate Cards Created for Each Quantity of Same Product During Shipment Creation for Transfer Orders

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/fulfillment-pwa#422]
## Current behavior
Each quantity of the same product within a transfer order generates a separate shipment card, leading to cluttered shipment management and potential confusion for users.

## Expected behavior
When creating shipments for transfer orders containing multiple quantities of the same product, the system should consolidate these quantities into a single shipment card for streamlined management and clarity.

## Steps to reproduce the issue
Open the App, select the facility from settings and then navigate to transfer order section.
Open any transfer order card.
Observe that separate shipment cards are generated for each quantity of the same product.
Observe the issue.

## Environment details
- App version: TRANSFER-ORDER-UI-D9CDF5B
- App environment: UAT

## Additional information
![Screenshot 2024-02-24 at 12 16 14 AM](https://github.com/hotwax/fulfillment-pwa/assets/158989293/15dac8b0-3009-4a72-a21e-cc1ef30dda0c)

**Comment by dt2patel** [comment]
Here the expectation is that the system will present as many items as are present in the order. If a SKU is repeated into multiple items then it will be shown as such. We can investigate why multi qty lines in NS are showing as single lines in HotWax. May be that explode order item is impacting here as well

**Comment by ravilodhi** [comment]
This has beed fixed at OMS Side under the following PR - 

https://git.hotwax.co/commerce/oms/-/merge_requests/4377
