### ISSUE TITLE
Add rejection reason configuration from UI

### ISSUE THREAD

**Issue by dt2patel** [hotwax/fulfillment-pwa#423]
## What is the motivation for adding/enhancing this feature?

As we start to build out the admin settings part of the fulfillment app, we'll add multiple different settings pages, the first one being rejection reasons.

All settings in the Admin section of the menu will need to be linked to a permission, we can use this permission:
SFA_ADMIN

The rejection settings are only managed form the find page, no detail page. Here is a link to the UI:
https://www.figma.com/file/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?type=design&node-id=34572-93339&mode=design&t=dePES6i08mxDHSQn-11

**Comment by Adameddy26** [comment]
Tested the existing functionality of this feature completely in release v2.1.0. Found few issues and raised the same.
