### ISSUE TITLE
Modify UI for Shipping Label Generation of Transfer Order and Reprint Option

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/fulfillment-pwa#427]
## Current behavior

- [ ] Generate Shipping Label Button:
Present on the review shipment page for transfer order products.

- [ ] Re-print Option:
Available on the UI regardless of the success or failure of shipping label generation.

- [ ] Show Label Error Option:
Available on the UI regardless of the success or failure of shipping label generation.

## Expected behavior

- [ ] Regenerate Shipping Label Button:
It should be renamed from "Generate Shipping Label" to "Re-generate Shipping Label" after successful label generation.
This would Indicate the ability to regenerate the shipping label for the respective transfer order product if needed.

- [ ] Re-print Option:
This option should be removed from the UI for both successful and unsuccessful shipping label generation scenarios.
It should be no longer present on the UI to reprint shipping labels, streamlining the interface.

- [ ] Show Label Error Option:
No longer should be displayed on successful shipping label generation for transfer order products.
This option should be hidden as there are no errors to display, reducing clutter and confusion.

## Steps to Reproduce - 
Log in the App with valid credentials.
Go to Transfer Orders(TO) section and open any TO.
Manually enter the quantity for shipment or simply scan the product and then update the quantity.
Navigate to the "Review Shipment" page.
Click on the "Generate Shipping Label" button.
After successful label generation, open the option list present on "Review Shipment" header bar.

## Environment details
- App version: TRANSFER-ORDER-UI-451FBD7
- App Environment: UAT

## Additional information
https://jam.dev/c/9dad179c-1118-42a8-b525-6bae81d343da

**Comment by ravilodhi** [comment]
This issue has been fixed in the following PR - https://github.com/hotwax/fulfillment-pwa/pull/432
