### ISSUE TITLE
Selected Quantity Not Reset to 0 on Transfer Order Details Page After Discarding Shipment from 'Review Shipments' Page.

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/fulfillment-pwa#429]
## Expected behavior
After discarding a shipment from the 'Review Shipments' page, the selected quantity of the product for shipment on the Transfer Order details page should be automatically reset to 0. 

## Steps to reproduce the issue
Log in the App with valid credentials.
Go to Transfer Orders(TO) section and open any TO.
Manually enter the quantity for shipment or simply scan the product and then update the quantity.
Navigate to the "Review Shipment" page.
Go back to Transfer Order detail page.
Observe the issue.

## Environment details
App version: TRANSFER-ORDER-UI-451FBD7
App Environment: UAT

## Additional information
https://jam.dev/c/35c80b5e-721e-4058-a9a4-6bd3692bae76

**Comment by ravilodhi** [comment]
This issue has been fixed in the following PR - https://github.com/hotwax/fulfillment-pwa/pull/432
