### ISSUE TITLE
Automatic Quantity Increase Beyond Ordered Quantity When Adjusting Transfer Order Product Quantity During Shipment Creation.

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/fulfillment-pwa#430]
## Expected behavior
When adjusting the quantity of a transfer order product during shipment creation, the system should enforce validation to prevent the quantity from exceeding the initially ordered quantity. Users should not be able to set the quantity beyond the ordered amount, and the system should cap the quantity accordingly.

## Steps to reproduce the issue
Log in the App with valid credentials.
Go to Transfer Orders(TO) section and open any TO.
Adjust the quantity of item using up arrow. Set it to number which is more than the ordered quantity.(If not replicated, then adjust the quantity to 1 using down arrow and then again increase it using up arrow)

## Environment details
App version: TRANSFER-ORDER-UI-451FBD7
App Environment: UAT

## Additional information
https://jam.dev/c/ce63302f-46c5-498b-805a-fa7378e3db06

**Comment by ravilodhi** [comment]
This issue has been fixed in the following PR - https://github.com/hotwax/fulfillment-pwa/pull/432
