### ISSUE TITLE
Enhance transfer order search

### ISSUE THREAD

**Issue by ravilodhi** [hotwax/fulfillment-pwa#438]
## What is the motivation for adding/enhancing this feature?
User should be able to search TOs by orderId, orderName, externalOrderId, productId, productName and internalName.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified and working fine in release version v2.0.1.
https://jam.dev/c/733553f6-728c-4ee7-a3c7-3d4a29fec045
