### ISSUE TITLE
Pick and Save Not Enabled & Order Items Invisible 

### ISSUE THREAD

**Issue by khushalidube-hwsys** [hotwax/fulfillment-pwa#454]
## Current behavior

Currently, there are two critical issues affecting our system:

1. Pick and Save Buttons Not Enabled: The Pick and Save buttons are not enabled in  the app. 

2. Order Items Invisible in Fulfilment App: Additionally, the order items are not visible in the fulfilment application. As a result, we are unable to fulfill orders promptly.

We tested this issue for order ID : SVC13094 in adoc-sv-oms

## Expected behavior

1. The Pick and Save buttons should be enabled, allowing our team to efficiently manage orders.
2. Order items should be visible within the fulfilment application to facilitate accurate order processing.

**Comment by ravilodhi** [comment]
This issues is due the dependency on OMS. The recent changes related to internationalInvoiceUrl (Custom document generation) were part of OMS 5.5.1 release. So in order to get it fix on adoc-sv-oms, need to be upgraded to 5.5.1.
