### ISSUE TITLE
Display an alert before leaving the page after reordering the rejection reasons

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/fulfillment-pwa#466]
## Current behavior

On reordering the rejection reasons, the save toast gets displayed, but then if the user changes the page, the toast is not removed and is always on the UI until `save` is not clicked.

## Expected behavior

The toast should be removed once the user leaves the page.

## Steps to reproduce the issue

1. Go to rejection reason page
2. Reorder the reasons
3. See that a toast asking to save the changes is displayed
4. Change the page by clicking the side menu
5. See that the toast is still on the UI asking to save changed, but when again moving to the rejection reasons page the reasons are displayed in the original order, so there is no use-case of displaying the toast once user leaves the page

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.1.0.
https://jam.dev/c/0cf3e50c-15f7-4f01-85f9-f12ee603e240
