### ISSUE TITLE
After searching a reason and if the list is previously reordered it does not persist the reordered sequence

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/fulfillment-pwa#469]
## Current behavior

When reordering to reasons and then searching for a specific reason and then clearing the search, then the reordered list is lost.

## Expected behavior

The reordered list should persist until user does not leave the page or clicks the save button

## Steps to reproduce the issue

1. Reorder the reasons
2. Search for any reason
3. Clear the search and verify that the original list is displayed instead of the reordered list

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by amansinghbais** [comment]
Based on discussion with @dt2patel sir, The searching with reordering might create confusion. And there not many reasons in our case.
Hence removing the searching form the rejection reasons page.
