### ISSUE TITLE
API endpoints are prepared using app url instead of oms url

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/fulfillment-pwa#504]
## Current behavior

For some specific apis the endpoints prepared uses the app's url for preparing the endpoint, thus the apis get failed in that case.

## Expected behavior

Api should not use app's url for preparing the endpoints

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.3.0. Hence, closing this ticket.
