### ISSUE TITLE
Issue with Picker Search Functionality

### ISSUE THREAD

**Issue by AjinkyaM1** [hotwax/fulfillment-pwa#506]
## Current behavior
We have an issue with the picker search function. Even though the picker is listed, searching for it by name doesn't yield any results. After entering the picker's name and hitting enter, the system fails to locate the picker. 

## Expected behavior
The system should display the picker corresponding to the entered name.

## Steps to reproduce the issue
1. Navigate to the picker search field.
2. Enter the name of the picker.
3.  Press enter. 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information
 JAM : - https://jam.dev/c/c5004022-695d-4689-9d6c-629bb3f36b0f

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.3.0. Hence, closing this ticket.
