### ISSUE TITLE
Use UTF-8 encoding in CSV export

### ISSUE THREAD

**Issue by dt2patel** [hotwax/fulfillment-pwa#509]
## Current behavior

When exporting CSVs from the fulfillment app, we need to ensure that they use UTF-8 encoding for maximum compatibly.

**Comment by ymaheshwari1** [comment]
Checked on the encoding when exporting packed orders csv and we are currently using UTF-8 encoding
https://github.com/hotwax/fulfillment-pwa/blob/main/src/utils/index.ts#L98

**Comment by ymaheshwari1** [comment]
Closing as working fine.
