### ISSUE TITLE
Add Order lookup feature

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/fulfillment-pwa#511]
## What are the acceptance criteria?

- [ ] Add page to list the orders and filters for sorting the orders
- [ ] Add support to view order details

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Enhancement changes verified in release v2.4.0. Three issues were found and reported to dev which are fixed and deployed. Therefore, marking this ticket as closed.
