### ISSUE TITLE
Alert Box Stays Open After Confirming 'Reject All' Orders

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/fulfillment-pwa#512]
## Expected behavior
After confirming the rejection in the alert box, the alert should close automatically, and the user should be able to see that the orders have been rejected without needing to refresh the page.
Also a loader should be visible indicating that the action is in progress.

## Steps to reproduce the issue
Log in to the App.
Select the "Open" or "In Progress" tab to view the list of orders.
Click on the "Reject All" option.
An alert box appears with a confirmation message.
Confirm the rejection to observe the issue.

## Environment details
App version : v2.3.0
App environment : UAT

## Additional information
https://jam.dev/c/baab41be-0d42-4d13-b2cb-77aedfff5b9d

**Comment by ymaheshwari1** [comment]
For this case, after confirming the rejection alert we will close the confirm alert and will display a loader. Its not expected that the orders will be removed from the page without refresh. Because there are cases where the data updation takes some time.

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.4.0.
https://jam.dev/c/30ff8a3e-5953-43f9-9cf8-583ba0a6eb49
Hence, closing this issue.
