### ISSUE TITLE
Update UI for the orderLookup page

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/fulfillment-pwa#518]
## What is the motivation for adding/enhancing this feature?

Currently we are displaying the products as cards on the orderLookup list page, but as per the suggestion we need to impove the UI by displaying products in ion-item.

- Each ion-item will contain product-information, facility, shipping method and item-status from left-to-right.
- Add an option to filter the records on the basis of orderDate. User will have option to select a from and to date, and will also have some hardcoded options to select from.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Enhancement changes verified in release 2.4.1 wherein found 2 issues.
1. Custom filter is not working properly.
2. Infinite scroll issue in order list. (all orders obeying the filter criteria are not getting fetched)

Hence, reopening this ticket.

**Comment by Adameddy26** [comment]
Enhancement changes verified in release 2.4.2 wherein found that the channels, date, brand filters in order lookup are not working when user login the app after logout using same OMS instance or changes the OMS instance.

Hence, reopening this issue.

**Comment by Adameddy26** [comment]
> Enhancement changes verified in release 2.4.2 wherein found that the channels, date, brand filters in order lookup are not working when user login the app after logout using same OMS instance or changes the OMS instance.
> 
> Hence, reopening this issue.

Verified the changes in release v2.4.3 and found that everything is working fine. Hence, closing this ticket.
