### ISSUE TITLE
Use default cursor on the rejection reasons list item

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/fulfillment-pwa#553]
## What is the motivation for adding/enhancing this feature?

Current we are showing cursor pointer on the rejection reason list item even though the item is not clickable. We should show default cursor instead.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Changes verified and working fine in release v2.4.3. Hence, closing this ticket.
https://jam.dev/c/63baae60-c98e-4bbb-a781-55bdee795cc0
